
hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  job_logging:
    root:
      level: INFO

debug: false
seed: 0
save_dir: "./exp/${wandb.group}/${wandb.name}"
resume: null
print_interval: 10
checkpoint: false

# Agent params 
agent1: 'DQN'
agent2: 'TitForTat'

# Environment parameters
num_envs: 20
episode_length: 50

# Training hyperparameters
num_episodes: 10000
eval_every: 500

# Agent params
batch_size: 256
lr: 3e-2
discount: 1
device: cuda
tau: 1.0
learning_rate: 1e-2
epsilon: 0.5
replay_capacity: 100000
min_replay_size: 1000
sgd_period: 1 
target_update_period: 4 

# Logging setup
wandb:
  entity: "ucl-dark"
  project: ipd
  group: '${agent1}-vs-${agent2}-testing-DQN'
  name: turns-${episode_length},gamma-${discount}-run-${seed}-epsilon-${epsilon}
  log: True
