
hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  job_logging:
    root:
      level: INFO

debug: false
seed: 0
save_dir: "./exp/${wandb.group}/${wandb.name}"
resume: null
print_interval: 10
checkpoint: false

# Agent params 
agent1: 'DQN'
agent2: 'TitForTat'

# Env params
# num_envs: 20
# episode_length: 100

# TEST Env params
num_envs: 20
episode_length: 50

# Training hyperparams
num_episodes: 10000
eval_every: 500

# TEST env params 
# num_episodes: 1000
# eval_every: 500

# train_episodes: 100
# eval_episodes: 100

# Agent params
batch_size: 256
lr: 3e-2
discount: 1
device: cuda
tau: 1.0
# uniform_weight: 0.0  # Add uniform weight to speaker
learning_rate: 1e-2
epsilon: 0.05
replay_capacity: 100000
min_replay_size: 1000
sgd_period: 1 
target_update_period: 4 

wandb:
  entity: "ucl-dark"
  project: ipd
  group: '${agent1}-vs-${agent2}-debug'
  name: turns-${episode_length},gamma-${discount}-run-${seed}-epislon-${epsilon}-optimistic-init
  log: True
