
hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  job_logging:
    root:
      level: INFO

debug: false
seed: 0
save_dir: "./exp/${wandb.group}/${wandb.name}"
resume: null
print_interval: 10
checkpoint: false

# Agent params 
agent1: 'DQN'
agent2: 'DQN'

# Environment parameters
num_envs: 50
episode_length: 50
payoff: [[2,2], [3,0], [0,3], [1,1]] # CC, DC, CD, DD 

# Training hyperparameters
num_episodes: 1000
eval_every: 50

# Agent params
batch_size: 256
discount: 0.99
device: cuda
tau: 1.0
learning_rate: 1e-2
epsilon: 0.5
replay_capacity: 100000
min_replay_size: 1000
sgd_period: 1 
target_update_period: 4 

# Logging setup
wandb:
  entity: "ucl-dark"
  project: ipd
  group: '${agent1}-vs-${agent2}-testing-new-class'
  name: ep-length=${episode_length},gamma=${discount},seed=${seed},epsilon=${epsilon}
  log: True
